baseURL: 'http://shirzartenwer.github.io/'
languageCode: en-us
title: Personal Blog

module:
  imports:
    - path: github.com/aormsby/hugo-shortcodes
    - path: github.com/aormsby/hugo-custom-layouts
    - path: github.com/aormsby/papermod-custom
    - path: github.com/adityatelange/hugo-PaperMod